/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class FormKonveksi extends javax.swing.JFrame {

    /**
     * Creates new form FormKonveksi
     */
    public FormKonveksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        lblPreOrder = new javax.swing.JLabel();
        PanelOrder = new javax.swing.JPanel();
        lblJenis = new javax.swing.JLabel();
        comboboxjenis = new javax.swing.JComboBox<>();
        lblWarna = new javax.swing.JLabel();
        txtFieldwarna = new javax.swing.JTextField();
        lblUkuran = new javax.swing.JLabel();
        lblTotalHarga = new javax.swing.JLabel();
        txtFieldTotalHarga = new javax.swing.JTextField();
        lblEstimasiWaktu = new javax.swing.JLabel();
        txtFieldEstimasiWaktu = new javax.swing.JTextField();
        lblUkuranS = new javax.swing.JLabel();
        lblUkuranM = new javax.swing.JLabel();
        txtFieldukuranS = new javax.swing.JTextField();
        txtFieldukuranM = new javax.swing.JTextField();
        lblUkuranL = new javax.swing.JLabel();
        txtFieldukuranL = new javax.swing.JTextField();
        lblUkuranXL = new javax.swing.JLabel();
        txtFieldukuranXL = new javax.swing.JTextField();
        lblUkuranXXL = new javax.swing.JLabel();
        txtFieldukuranXXL = new javax.swing.JTextField();
        lblNama = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        lblNoHP = new javax.swing.JLabel();
        lblTanggalPemesanan = new javax.swing.JLabel();
        txtFieldTanggalPemesanan = new javax.swing.JTextField();
        txtFieldNamaPemesan = new javax.swing.JTextField();
        txtFieldNoHP = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblAdmin = new javax.swing.JLabel();
        txtFieldAdmin = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        checkboxWaiting = new java.awt.Checkbox();
        checkboxProcess = new java.awt.Checkbox();
        checkboxDeliveryTime = new java.awt.Checkbox();
        checkboxDelivered = new java.awt.Checkbox();
        btnKeluar = new javax.swing.JButton();
        txtFieldAlamat = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 51));

        lblPreOrder.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        lblPreOrder.setText("DanDy Convection");

        PanelOrder.setBackground(new java.awt.Color(102, 102, 255));
        PanelOrder.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        lblJenis.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblJenis.setForeground(new java.awt.Color(255, 255, 255));
        lblJenis.setText("Jenis");

        comboboxjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kaos Oblong Polos", "Kaos Oblong Bordir", "Kaos Oblong Costum", "Kemeja Pendek Bordir", "Kemeja Panjang Bordir", " " }));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, checkboxWaiting, org.jdesktop.beansbinding.ObjectProperty.create(), comboboxjenis, org.jdesktop.beansbinding.BeanProperty.create("border"));
        bindingGroup.addBinding(binding);

        comboboxjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxjenisActionPerformed(evt);
            }
        });

        lblWarna.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        lblWarna.setForeground(new java.awt.Color(255, 255, 255));
        lblWarna.setText("Warna");

        txtFieldwarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldwarnaActionPerformed(evt);
            }
        });

        lblUkuran.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblUkuran.setForeground(new java.awt.Color(255, 255, 255));
        lblUkuran.setText("Ukuran");

        lblTotalHarga.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        lblTotalHarga.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalHarga.setText("Total Harga");

        lblEstimasiWaktu.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblEstimasiWaktu.setForeground(new java.awt.Color(255, 255, 255));
        lblEstimasiWaktu.setText("Estimasi Waktu");

        lblUkuranS.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblUkuranS.setForeground(new java.awt.Color(255, 255, 255));
        lblUkuranS.setText("S");

        lblUkuranM.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblUkuranM.setForeground(new java.awt.Color(255, 255, 255));
        lblUkuranM.setText("M");

        txtFieldukuranS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldukuranSActionPerformed(evt);
            }
        });

        lblUkuranL.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblUkuranL.setForeground(new java.awt.Color(255, 255, 255));
        lblUkuranL.setText("L");

        txtFieldukuranL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldukuranLActionPerformed(evt);
            }
        });

        lblUkuranXL.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblUkuranXL.setForeground(new java.awt.Color(255, 255, 255));
        lblUkuranXL.setText("XL");

        lblUkuranXXL.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblUkuranXXL.setForeground(new java.awt.Color(255, 255, 255));
        lblUkuranXXL.setText("XXL");

        txtFieldukuranXXL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldukuranXXLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelOrderLayout = new javax.swing.GroupLayout(PanelOrder);
        PanelOrder.setLayout(PanelOrderLayout);
        PanelOrderLayout.setHorizontalGroup(
            PanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelOrderLayout.createSequentialGroup()
                        .addComponent(lblEstimasiWaktu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldEstimasiWaktu))
                    .addGroup(PanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelOrderLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addGroup(PanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblUkuranM)
                                    .addComponent(lblUkuranS))
                                .addGroup(PanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelOrderLayout.createSequentialGroup()
                                        .addComponent(lblUkuranXXL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtFieldukuranXXL, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelOrderLayout.createSequentialGroup()
                                        .addGroup(PanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblUkuranXL)
                                            .addComponent(lblUkuranL))
                                        .addGap(80, 80, 80)
                                        .addGroup(PanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtFieldukuranL, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                            .addComponent(txtFieldukuranM)
                                            .addComponent(txtFieldukuranXL)
                                            .addComponent(txtFieldukuranS))))
                                .addGroup(PanelOrderLayout.createSequentialGroup()
                                    .addGap(98, 98, 98)
                                    .addComponent(comboboxjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(lblJenis)
                        .addComponent(lblWarna)
                        .addComponent(lblUkuran)
                        .addComponent(txtFieldwarna, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelOrderLayout.createSequentialGroup()
                        .addComponent(lblTotalHarga)
                        .addGap(18, 18, 18)
                        .addComponent(txtFieldTotalHarga)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        PanelOrderLayout.setVerticalGroup(
            PanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJenis)
                    .addComponent(comboboxjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldwarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWarna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUkuran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUkuranS)
                    .addComponent(txtFieldukuranS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(PanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUkuranM)
                    .addComponent(txtFieldukuranM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUkuranL)
                    .addComponent(txtFieldukuranL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUkuranXL)
                    .addComponent(txtFieldukuranXL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUkuranXXL)
                    .addComponent(txtFieldukuranXXL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstimasiWaktu)
                    .addComponent(txtFieldEstimasiWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lblNama.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        lblNama.setText("Nama");

        lblAlamat.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblAlamat.setText("Alamat");

        lblNoHP.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        lblNoHP.setText("No.HP");

        lblTanggalPemesanan.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        lblTanggalPemesanan.setText("Tanggal Pemesanan");

        txtFieldNamaPemesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNamaPemesanActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tanggal Pemesanan", "Nama", "Alamat", "No.HP", "Admin", "Jenis", "Warna", "Total Harga", "Estimasi", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        lblAdmin.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblAdmin.setText("Admin");

        txtFieldAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldAdminActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(51, 51, 51));
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        checkboxWaiting.setLabel("Waiting");

        checkboxProcess.setLabel("Process");

        checkboxDeliveryTime.setLabel("DeliveryTime");

        checkboxDelivered.setLabel("Delivered");

        btnKeluar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(lblPreOrder))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnKeluar)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(checkboxWaiting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(checkboxProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkboxDeliveryTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkboxDelivered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(91, 91, 91))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(PanelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNama)
                                            .addComponent(lblAlamat)
                                            .addComponent(lblNoHP)
                                            .addComponent(lblAdmin)
                                            .addComponent(lblTanggalPemesanan))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtFieldNamaPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldTanggalPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldNoHP, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPreOrder)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTanggalPemesanan)
                            .addComponent(txtFieldTanggalPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNama)
                            .addComponent(txtFieldNamaPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAlamat)
                                .addGap(48, 48, 48)
                                .addComponent(lblNoHP))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(txtFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFieldNoHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAdmin)
                            .addComponent(txtFieldAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkboxWaiting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxDeliveryTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxDelivered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKeluar)
                .addGap(125, 125, 125))
        );

        checkboxWaiting.getAccessibleContext().setAccessibleName("");
        checkboxWaiting.getAccessibleContext().setAccessibleParent(checkboxWaiting);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxjenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxjenisActionPerformed

    private void txtFieldwarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldwarnaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtFieldwarnaActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtFieldukuranSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldukuranSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldukuranSActionPerformed

    private void txtFieldukuranLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldukuranLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldukuranLActionPerformed

    private void txtFieldukuranXXLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldukuranXXLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldukuranXXLActionPerformed

    private void txtFieldNamaPemesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNamaPemesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldNamaPemesanActionPerformed

    private void txtFieldAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKonveksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKonveksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKonveksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKonveksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKonveksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelOrder;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSave;
    private java.awt.Checkbox checkboxDelivered;
    private java.awt.Checkbox checkboxDeliveryTime;
    private java.awt.Checkbox checkboxProcess;
    private java.awt.Checkbox checkboxWaiting;
    private javax.swing.JComboBox<String> comboboxjenis;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblEstimasiWaktu;
    private javax.swing.JLabel lblJenis;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNoHP;
    private javax.swing.JLabel lblPreOrder;
    private javax.swing.JLabel lblTanggalPemesanan;
    private javax.swing.JLabel lblTotalHarga;
    private javax.swing.JLabel lblUkuran;
    private javax.swing.JLabel lblUkuranL;
    private javax.swing.JLabel lblUkuranM;
    private javax.swing.JLabel lblUkuranS;
    private javax.swing.JLabel lblUkuranXL;
    private javax.swing.JLabel lblUkuranXXL;
    private javax.swing.JLabel lblWarna;
    private javax.swing.JTextField txtFieldAdmin;
    private javax.swing.JTextField txtFieldAlamat;
    private javax.swing.JTextField txtFieldEstimasiWaktu;
    private javax.swing.JTextField txtFieldNamaPemesan;
    private javax.swing.JTextField txtFieldNoHP;
    private javax.swing.JTextField txtFieldTanggalPemesanan;
    private javax.swing.JTextField txtFieldTotalHarga;
    private javax.swing.JTextField txtFieldukuranL;
    private javax.swing.JTextField txtFieldukuranM;
    private javax.swing.JTextField txtFieldukuranS;
    private javax.swing.JTextField txtFieldukuranXL;
    private javax.swing.JTextField txtFieldukuranXXL;
    private javax.swing.JTextField txtFieldwarna;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
